apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-service
  namespace: monorepo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: go-service
  template:
    metadata:
      labels:
        app: go-service
    spec:
      containers:
        - name: go-service
          image: ghcr.io/ndrwj/monorepo-cfx/services/go-service
          ports:
            - containerPort: 8080